name = "live-event"
pages_build_output_dir = "./docs"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "live-event-db"
# ↓ Cloudflareで作ったD1データベースのIDに書き換えてください（README参照）
database_id = "f2bc710a-4b1f-480a-b050-f3d56b440bbf"
